version: "3"

services:
  database: 
    image: bitnami/postgresql:latest
    restart: always
    tty: true
    env_file: ".env"
    ports:
      - 5454:5432  # Remove this on productionzwszsSÍ
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql

  backend:
    links:
      - database
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    tty: true
    env_file: ".env"
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend:/app

  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   privileged: true
  #   restart: always
  #   stdin_open: true
  #   tty: true
  #   command: /bin/sh
  #   volumes:
  #     - ./frontend:/src